# Control file for continuous integration testing at http://travis-ci.org/
language: r
r: bioc-devel
dist: trusty

matrix:
  include:
    # OSX begin
    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc@5 && brew install r && CC=gcc-5 && CXX=g++-5"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc@6 && brew install r && CC=gcc-6 && CXX=g++-6"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc@7 && brew install r && CC=gcc-7 && CXX=g++-7"

    - os: osx
      osx_image: xcode10
      env:
        - MATRIX_EVAL="brew update && brew install gcc@8 && brew install r && CC=gcc-8 && CXX=g++-8"


before_install:
  - eval "${MATRIX_EVAL}"
  - mkdir -p ~/.R && rm -f ~/.R/Makevars
  - echo "CC=${CC} -std=gnu99" >> ~/.R/Makevars
  - echo "CXX=${CXX}" >> ~/.R/Makevars
  - echo "CXX1X=${CXX} -std=c++0x" >> ~/.R/Makevars
  - echo "CXX11=${CXX} -std=c++0x" >> ~/.R/Makevars

script:
  - git submodule update --recursive
  - cat ~/.R/Makevars
  - R CMD INSTALL . --no-staged-install